<template>
    <Head title="Terms & Conditions" />

    <div class="terms-page">
        <!-- Starfield background -->
        <div class="stars" aria-hidden="true">
            <span v-for="n in 60" :key="n" class="star" :style="starStyle(n)" />
        </div>

        <!-- Constellation lines decoration -->
        <svg class="constellation" aria-hidden="true" viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg">
            <line x1="50" y1="80" x2="180" y2="140" stroke="rgba(201,168,76,0.08)" stroke-width="1" />
            <line x1="180" y1="140" x2="300" y2="90" stroke="rgba(201,168,76,0.08)" stroke-width="1" />
            <line x1="300" y1="90" x2="350" y2="200" stroke="rgba(201,168,76,0.08)" stroke-width="1" />
            <circle cx="50" cy="80" r="2" fill="rgba(201,168,76,0.3)" />
            <circle cx="180" cy="140" r="2" fill="rgba(201,168,76,0.3)" />
            <circle cx="300" cy="90" r="2" fill="rgba(201,168,76,0.3)" />
            <circle cx="350" cy="200" r="2" fill="rgba(201,168,76,0.3)" />
        </svg>

        <div class="container">
            <!-- Header -->
            <header class="page-header">
                <div class="emblem">✦</div>
                <h1 class="title">My Astro Sathi</h1>
                <p class="subtitle">Terms &amp; Conditions</p>
                <div class="header-divider">
                    <span class="divider-line" />
                    <span class="divider-star">★</span>
                    <span class="divider-line" />
                </div>
            </header>

            <!-- Intro -->
            <p class="intro">
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p class="intro" style="margin-top: -24px;">
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://myastrosathi.com/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
            </p>

            <!-- Sections -->
            <section v-for="(section, index) in sections" :key="section.title" class="terms-section"
                :style="{ animationDelay: index * 0.06 + 's' }">
                <div class="section-header">
                    <span class="section-number">{{ String(index + 1).padStart(2, '0') }}</span>
                    <span class="section-icon">{{ section.icon }}</span>
                    <h2 class="section-title">{{ section.title }}</h2>
                </div>
                <div class="section-body">
                    <p v-for="(para, pi) in section.paragraphs" :key="pi" class="section-text" v-html="para" />
                    <ul v-if="section.bullets" class="terms-list">
                        <li v-for="(bullet, bi) in section.bullets" :key="bi" class="terms-list-item">
                            {{ bullet }}
                        </li>
                    </ul>
                </div>
            </section>

            <!-- Acceptance notice -->
            <div class="acceptance-box">
                <span class="acceptance-icon">✦</span>
                <p class="acceptance-text">
                    ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING..
                </p>
            </div>

            <!-- Contact -->
            <section class="contact-section">
                <div class="section-icon-lg">✉️</div>
                <div>
                    <h2 class="section-title">Contact &amp; Grievances</h2>
                    <p class="section-text">
                        All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website
                    </p>
                </div>
            </section>

            <footer class="page-footer">
                <span>✦ My Astro Sathi — Written in the Stars ✦</span>
            </footer>
        </div>
    </div>
</template>

<script setup>
import { Head } from '@inertiajs/vue3';

const sections = [
    {
        icon: '🏢',
        title: 'Platform Ownership',
        paragraphs: [
            'The Platform is owned by 9752337971, a company incorporated under the Companies Act, 1956 with its registered office at 12 Ext Lokmanya Nagar  (hereinafter referred to as ‘Platform Owner’, \'we\', \'us\', \'our\')..'
        ],
    },
    {
        icon: '📜',
        title: 'Applicability of Terms',
        paragraphs: [
            'Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, \'Services\'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates..',
            'For the purpose of these Terms of Use, wherever the context so requires ‘you’, \'your\' or ‘user’ shall mean any natural or legal person who has agreed to become a user/buyer on the Platform..'
        ],
    },
    {
        icon: '⚖️',
        title: 'Conditions of Use',
        paragraphs: [
            'The use of Platform and/or availing of our Services is subject to the following Terms of Use:'
        ],
        bullets: [
            'To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform..',
            'Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law..',
            'Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements..',
            'The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics..',
            'You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws..',
            'You agree to pay us the charges associated with availing the Services..',
            'You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.',
            'You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information..',
            'You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services..',
            'You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney\'s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.',
            'Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event..',
            'These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India..',
            'All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in  and .'
        ],
    }
]

function starStyle(n) {
    const size = (((n * 7) % 3) + 1)
    return {
        width: size + 'px',
        height: size + 'px',
        top: ((n * 137.5) % 100) + '%',
        left: ((n * 97.3) % 100) + '%',
        animationDelay: (n * 0.3) % 5 + 's',
        animationDuration: 3 + (n % 4) + 's',
    }
}
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Lato:wght@300;400&display=swap');

/* ─── Base ─────────────────────────────────────── */
.terms-page {
    min-height: 100vh;
    background: #0a0614;
    color: #e8dff5;
    font-family: 'Lato', sans-serif;
    font-weight: 300;
    position: relative;
    overflow-x: hidden;
}

/* ─── Starfield ─────────────────────────────────── */
.stars {
    position: fixed;
    inset: 0;
    pointer-events: none;
    z-index: 0;
}

.star {
    position: absolute;
    border-radius: 50%;
    background: #fff;
    opacity: 0;
    animation: twinkle linear infinite;
}

@keyframes twinkle {

    0%,
    100% {
        opacity: 0;
    }

    50% {
        opacity: 0.7;
    }
}

/* ─── Constellation SVG ─────────────────────────── */
.constellation {
    position: fixed;
    top: 0;
    right: 0;
    width: 400px;
    height: 400px;
    pointer-events: none;
    z-index: 0;
    opacity: 0.6;
}

/* ─── Layout ────────────────────────────────────── */
.container {
    position: relative;
    z-index: 1;
    max-width: 800px;
    margin: 0 auto;
    padding: 60px 24px 80px;
}

/* ─── Header ────────────────────────────────────── */
.page-header {
    text-align: center;
    margin-bottom: 44px;
}

.emblem {
    font-size: 2.2rem;
    color: #c9a84c;
    margin-bottom: 12px;
    display: block;
    animation: pulse 3s ease-in-out infinite;
}

@keyframes pulse {

    0%,
    100% {
        opacity: 1;
        transform: scale(1);
    }

    50% {
        opacity: 0.7;
        transform: scale(1.15);
    }
}

.title {
    font-family: 'Cinzel', serif;
    font-size: clamp(1.8rem, 5vw, 2.8rem);
    font-weight: 700;
    color: #f0e6c8;
    letter-spacing: 0.08em;
    margin: 0 0 6px;
}

.subtitle {
    font-family: 'Cinzel', serif;
    font-size: 1rem;
    color: #c9a84c;
    letter-spacing: 0.22em;
    text-transform: uppercase;
    margin: 0 0 20px;
}

.header-divider {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 12px;
}

.divider-line {
    display: block;
    width: 80px;
    height: 1px;
    background: linear-gradient(to right, transparent, rgba(201, 168, 76, 0.5), transparent);
}

.divider-star {
    color: #c9a84c;
    font-size: 0.7rem;
    opacity: 0.8;
}

/* ─── Intro ─────────────────────────────────────── */
.intro {
    text-align: center;
    font-size: 0.96rem;
    line-height: 1.85;
    color: #c5b8d8;
    margin-bottom: 48px;
    padding: 22px 28px;
    border: 1px solid rgba(201, 168, 76, 0.18);
    border-radius: 12px;
    background: rgba(201, 168, 76, 0.04);
}

.intro strong {
    color: #f0e6c8;
    font-weight: 400;
}

/* ─── Terms Sections ────────────────────────────── */
.terms-section {
    padding: 28px 0;
    border-bottom: 1px solid rgba(148, 128, 176, 0.12);
    animation: fadeUp 0.5s ease both;
}

.terms-section:last-of-type {
    border-bottom: none;
}

@keyframes fadeUp {
    from {
        opacity: 0;
        transform: translateY(14px);
    }

    to {
        opacity: 1;
        transform: translateY(0);
    }
}

.section-header {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 14px;
}

.section-number {
    font-family: 'Cinzel', serif;
    font-size: 0.72rem;
    color: #6a5880;
    letter-spacing: 0.1em;
    min-width: 24px;
}

.section-icon {
    font-size: 1.2rem;
    filter: drop-shadow(0 0 5px rgba(201, 168, 76, 0.35));
}

.section-title {
    font-family: 'Cinzel', serif;
    font-size: 0.98rem;
    font-weight: 600;
    color: #f0e6c8;
    letter-spacing: 0.06em;
    margin: 0;
}

.section-body {
    padding-left: 36px;
}

.section-text {
    font-size: 0.92rem;
    line-height: 1.85;
    color: #b8aac8;
    margin: 0 0 10px;
}

.section-text:last-child {
    margin-bottom: 0;
}

/* ─── Bullet list ───────────────────────────────── */
.terms-list {
    list-style: none;
    padding: 0;
    margin: 10px 0 0;
}

.terms-list-item {
    font-size: 0.91rem;
    line-height: 1.8;
    color: #b8aac8;
    padding: 6px 0 6px 22px;
    position: relative;
    border-bottom: 1px solid rgba(148, 128, 176, 0.08);
}

.terms-list-item:last-child {
    border-bottom: none;
}

.terms-list-item::before {
    content: '✦';
    position: absolute;
    left: 0;
    top: 8px;
    font-size: 0.5rem;
    color: #c9a84c;
    opacity: 0.7;
}

/* ─── Acceptance box ────────────────────────────── */
.acceptance-box {
    display: flex;
    gap: 16px;
    align-items: flex-start;
    background: rgba(201, 168, 76, 0.06);
    border: 1px solid rgba(201, 168, 76, 0.28);
    border-radius: 12px;
    padding: 24px 28px;
    margin: 40px 0 24px;
}

.acceptance-icon {
    font-size: 1.4rem;
    color: #c9a84c;
    min-width: 24px;
    text-align: center;
    margin-top: 2px;
    animation: pulse 3s ease-in-out infinite;
}

.acceptance-text {
    font-size: 0.92rem;
    line-height: 1.85;
    color: #c5b8d8;
    margin: 0;
}

.acceptance-text strong {
    color: #f0e6c8;
    font-weight: 400;
}

/* ─── Contact section ───────────────────────────── */
.contact-section {
    display: flex;
    gap: 20px;
    align-items: flex-start;
    padding: 28px 0 0;
}

.section-icon-lg {
    font-size: 1.4rem;
    min-width: 40px;
    text-align: center;
    filter: drop-shadow(0 0 6px rgba(201, 168, 76, 0.4));
    padding-top: 2px;
}

/* ─── Links ─────────────────────────────────────── */
.link {
    color: #c9a84c;
    text-decoration: none;
    border-bottom: 1px solid rgba(201, 168, 76, 0.35);
    transition: color 0.2s, border-color 0.2s;
    margin-left: 4px;
}

.link:hover {
    color: #f0d98a;
    border-color: #f0d98a;
}

/* ─── Footer ────────────────────────────────────── */
.page-footer {
    text-align: center;
    margin-top: 56px;
    font-family: 'Cinzel', serif;
    font-size: 0.78rem;
    color: #6a5880;
    letter-spacing: 0.12em;
}
</style>